general.import = ["~/.config/alacritty/dracula.toml"]

# font setting
[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
  startup_mode = "Maximized"
  decorations = "none"
  opacity = 0.9
  decorations_theme_variant = "Dark"
  padding = {x = 10, y = 10}
  dynamic_title = false
  title = "Alacritty"
