[modules]
left = [
    [
    "Workspaces",
    "WindowTitle",
    ]
]
center = [
        "Clock",
        "MediaPlayer"
    ]
right = [
    "Tray",
    [
        "Updates",
        "SystemInfo",
    ],
    "Settings",
]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = "kitty --hold yay -Syu"

[window_title]
mode = "Class"
truncate_title_after_length = 75

[appearance]
scale_factor = 1.2
_style = "Islands"
primary_color = "#f2be6e"
success_color = "#b6cea3"
text_color = "#f2be6e"

workspace_colors = [
    "#f2be6e",
    "#b6cea3"
]
special_workspace_colors = [
    "#f2be6e",
    "#b6cea3"
]

[appearance.menu]
opacity = 0.9

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true

[workspaces]
enable_workspace_filling = true
max_workspaces = 10
enable_special_workspaces = false